# Generated by Django 2.2.4 on 2021-05-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_book_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='DBdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='DBtitle',
            new_name='title',
        ),
    ]
